### ISSUE TITLE
EXAMPLE: As a researcher, I want to inform repository operator on the amount of data in the planning phase, so that they confirm that they will accept later my submission.

### ISSUE THREAD

**Issue by RDA-DMP-Common** [RDA-DMP-Common/user-stories#1]
This is needed in the planning phase. Researchers need to estimate the amount of data produced in the project. They need to contact the repository to make sure that repository will be able (an is willing) to ingest the data when the researchers have the data.

**Comment by RDA-DMP-Common** [comment]
The researcher will likely use one of the DMP platforms with questionnaires to provide this information. Will this information be consumed directly by a repository system?

**Comment by martateperek** [comment]
This will be also needed to estimate the costs of data management for the project - so the information is relevant not only to repository managers but also to funding bodies, IT (who will support the project during research data lifecycle).
