### ISSUE TITLE
As a data manager, I want the description of data sets collected or used, updated throughout the project lifecycle, to ensure the descriptions are current and add detail as the study proceeds.

### ISSUE THREAD

**Issue by dwalt** [RDA-DMP-Common/user-stories#106]

**Comment by TomMiksa** [comment]
Could you please specify what kind of information you would expect in a description?

**Comment by dwalt** [comment]
Description varies throughout a project lifecycle, so my use story is about
increasing the granularity and normalization of descriptions as well as
currency, throughout the project lifecycle. At the beginning of a project,
specifics about may be as yet unclear and perhaps not relevant. But as
decisions are made, the DMP should be updated to reflect current knowledge.
For example, we may describe the collection of weather data in general
terms during the funding stage. As the project becomes funded and we move
into the planning stage we may specify attributing, such as temperature and
humidity, and relevant units of measure, precision and sensor information.
It may include protocols to be applied, updated sizing estimates, or
identify new data types not initially considered during earlier stages.

**Comment by paulwalk** [comment]
This is an interesting user-story - it's slightly out-of-scope of our exercise here because it is more about enabling updates than the data model itself, but I think we should keep this one in scope because it also has something to say about the type and granularity of the data model.
