### ISSUE TITLE
As a data manager, I want to ensure roles and responsibilities are well defined.

### ISSUE THREAD

**Issue by dwalt** [RDA-DMP-Common/user-stories#108]

**Comment by paulwalk** [comment]
reviewed.

**Comment by jludwig1** [comment]
I‘m not sure whether it is out of scope. The roles and responsibilities can be part of a DMP, don‘t you think? Whether they are well defined is a different matter.

**Comment by TomMiksa** [comment]
Yes, responsibilites can be a part of a DMP. It is not clear:
- when?
- why?
(and who is data manager)

**Comment by jludwig1** [comment]
My opinion: It is part of the planning phase and the person responsible for planning the data management needs to make sure that there is somebody responsible for every defined action. Similiar to a project proposal an assigning partners to tasks.

**Comment by dwalt** [comment]
Role and responsibilities are both people and organizations. Identifying
the data owner, funding organization, principal investigator, data steward,
data manager, archivist, distributor are a few roles and responsibilities I
would want to know about in a DMP.
