### ISSUE TITLE
As a manager I want to know about all resources and services used for the data so that I can estimate the true cost of the project 

### ISSUE THREAD

**Issue by jludwig1** [RDA-DMP-Common/user-stories#35]

**Comment by TomMiksa** [comment]
Who is the manager? The head of an instituiton, or the researchers planning their projects?

**Comment by jludwig1** [comment]
I think to some extent it is a duplicate of #71. But researchers like in #71 are often focused on the cost they have to put in the application. But often an institution has additional costs of which researchers are not aware or projects are explictly subsidized. Storage is a good example. With „manager“ in this user story I mean the head of an institution or another person responsible for ressource management that has to make sure that the institution has enough capactiy for the project.

**Comment by TomMiksa** [comment]
We've decieded to add a new label: ITresource to capture user stories that express a need for describing resources: storage, hardware, sensors, etc.
I guess the labeling is correct now.
