### ISSUE TITLE
As a funder, I want to request different information at different stages in the funding process

### ISSUE THREAD

**Issue by carrieseltzer** [RDA-DMP-Common/user-stories#4]
The kind of questions/information required at the proposal stage may be much simpler compared to what will be required at the award stage (or beginning of the project).

**Comment by RDA-DMP-Common** [comment]
Can you provide examples of information you would ask for at the proposal stage? What would be the absolute minimum for you?

**Comment by paulwalk** [comment]
Needs examples, or to be broken down into user stories
