### ISSUE TITLE
As a researcher I want to have our IT department fill the information of the standard processes in the organisation in my DMP in order to save me time.

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/user-stories#40]

**Comment by TomMiksa** [comment]
This issue is quite broad. I suppose it applies to the planning phase when a rough estimation is possible. The question is: which information is 'standard'.

**Comment by rwwh** [comment]
I intended this indeed for help with the planning phase. Any procedural descriptions that are always the same in the institute (e.g. backup policy, retention strategy, URL of institutional repository where all data will be deposited, links to data sharing policy document, ....) can and should be filled in automatically.

**Comment by paulwalk** [comment]
I am adding the 'integration/automation' tag to this because I think that, while this information could be added manually by IT staff, this information is more likely to be supplied in some (semi)automated fashion in a DMP tool of some kind.

**Comment by TomMiksa** [comment]
I think this exactly what we expect from maDMPs, but doesn't help us much with the MODEL itself. I would move it to the out of scope.

**Comment by paulwalk** [comment]
agreed.
