### ISSUE TITLE
As a repository owner I would like to be able to check the planned provenance of the data that will be submitted at the end of a project in order to check whether it belongs to our target group and in order to calculate necessary submission fees.

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/user-stories#43]

**Comment by TomMiksa** [comment]
Does it mean you would like to know what kind of content type will be produced and how?
For example: collection of JPEGs based on observations?

**Comment by paulwalk** [comment]
We are finding this difficult to process, but we think it has valuable aspects. Perhaps this should be broken down into separate user stories? Please advise! :-)

**Comment by rwwh** [comment]
You probablty know I am not a repository owner IRL, but I can try to deepen it a little. I'll leave potential splitting to you....

JPGs is a reasonable example. But is there a repository that will take any image as long as it is JPG?

I make a distinction between "generic repositories" and "discipline specific repositories". The target for this ticket is the latter. A discipline specific repository for language research will not only have the option of downloading an audio file, but can play and search it through the user interface. Similarly a repository built for human genomes can browse genomes and search for known variants. A generic repository is unlikely to have such specific funding (or it will, as the Germans say, become an [Eierlegende Wollmilchsau](https://en.wiktionary.org/wiki/eierlegende_Wollmilchsau))

Instead of "any JPG" I was more thinking of a hypothetical  "repository of chest X-rays of people with a diagnose of lung cancer". Or "repository only containing chest X-rays in which the aorta is visible". 

Checking through the DMP it should be possible for a repository to identify whether they would like to host the data, and potentially how much deposition would cost.

Does this help?

**Comment by paulwalk** [comment]
Thank you - that does help!

I suggest we include this - it's essentially about capturing sufficient information in the DMP that a repository owner or someone in a similar support position can make intelligent decisions about where to direct data for deposit
