### ISSUE TITLE
As a funder I would like to be able to read the costs for data management from the DMP in order to check whether our policies work as intended.

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/user-stories#44]

**Comment by martateperek** [comment]
Good point, and other stakeholders will want to know it as well for other purposes, e.g.:

- As a data steward I would like to see the data management costs to see if these were budgeted correctly and allow cost recovery
- As an IT manager I would like to see the the data management costs to see if these were budgeted correctly and would allow purchasing of sufficient storage space for the data
- As a data steward I would like to see the the data management costs to know whether researchers at my faculty overall are budgeting enough money overall for data management
