### ISSUE TITLE
As a researcher, I want to know topics mandatory and similar in all DMPs, so that I can quickly write it and save time.

### ISSUE THREAD

**Issue by TomMiksa** [RDA-DMP-Common/user-stories#58]
Based on the workshop outputs: https://doi.org/10.5281/zenodo.1067753

**Comment by paulwalk** [comment]
I think this is asking for 'templates'?

**Comment by TomMiksa** [comment]
I think this is asking for automation as well, so that answers are automatically generated. 
Again, I would consider it as a meta problem and out of scope.

**Comment by jludwig1** [comment]
I agree, I would consider it as out of scope too.
