### ISSUE TITLE
As a legal officer, I want to know about data sensitivity, to establish sharing options.

### ISSUE THREAD

**Issue by TomMiksa** [RDA-DMP-Common/user-stories#61]
Based on the workshop outputs: https://doi.org/10.5281/zenodo.1067753

**Comment by paulwalk** [comment]
Isn't this more for the 'repository manager', rather than a 'service provider'?

**Comment by TomMiksa** [comment]
This can be also understood as managing data during the project - configuring a workspace on a central server (internal cloud).
We can keep both stakeholders.
