### ISSUE TITLE
As a PI, I want to properly record all metadata so I can ensure proper running of the project in case of staff changes.

### ISSUE THREAD

**Issue by TomMiksa** [RDA-DMP-Common/user-stories#85]
Based on the workshop outputs: https://doi.org/10.5281/zenodo.1067753

**Comment by TomMiksa** [comment]
Out of scope

**Comment by paulwalk** [comment]
I am not sure... I think this is saying that the DMP needs to have sufficient information in the DMP that it can be executed by people who are unfamiliar with the project. This is about comprehensiveness of data
