### ISSUE TITLE
As a PI, I want to record information about my DMP such that an Ethics Committee can review this for compliance with ethical standards.

### ISSUE THREAD

**Issue by TomMiksa** [RDA-DMP-Common/user-stories#86]
Based on the workshop outputs: https://doi.org/10.5281/zenodo.1067753

**Comment by paulwalk** [comment]
Not sure I understand this one... out of scope?

**Comment by TomMiksa** [comment]
This one links to ethics reviews, for example, medical universities check whether you're allowed do research based on your methodology. DMPs complement the methdology description in fact. 

Hence, this user stories describes need to include information on other policies that apply to creation data, such as 'ethical' codes of conduct, etc. DMP should also include information whether the data is private or sensitive. I would keep this user story.
