### ISSUE TITLE
As a researcher, I want to extract of the description of the data collected so that I can reuse it for the writing of a data paper.

### ISSUE THREAD

**Issue by JacquemotMC** [RDA-DMP-Common/user-stories#90]

**Comment by paulwalk** [comment]
We interpret this to mean that the researcher wants to be able to get a formatted metadata record of the properties describing the data collected in the project so that they can cite these in a paper

**Comment by JacquemotMC** [comment]
The information (methodology, quality, ...) and metadata could be reused for the writing of a data paper.
