### ISSUE TITLE
As a researcher, I want to import metadata that I captured with a metadata tool so that I do not have to capture it again in a DMP.

### ISSUE THREAD

**Issue by JacquemotMC** [RDA-DMP-Common/user-stories#91]

**Comment by paulwalk** [comment]
This is on the borderline of being out of scope for this exercise, but I will accept this as we will certainly need to look at accommodating existing metadata profiles

**Comment by TomMiksa** [comment]
I would rather put into out of scope: I don't see any fields that could go into a model.

**Comment by JacquemotMC** [comment]
We collected this user stories from researchers and bioinformatician who capture metadata according to ISA Tab standard.  This standard enables a very detailed and structured description of the data in particular regarding samples, materials, protocols, quality controls that can be then reused for DMPs. It would allow to avoid a double seizure of this information.

**Comment by TomMiksa** [comment]
Ok, thank you. So I guess that we could either import some of the fields into a DMP, or simply reference them, so that we do not duplicate information.

**Comment by paulwalk** [comment]
I think this is in scope - essentially it is saying that the data model will need to interoperate with other schemas. The difficulty will be in identifying which other schemas - or devising a way to accommodate diverse other schemas.

In any case, we need to consider this in the data modelling
